In [2]:
## Imports
from src.print import *
import numpy as np

---
# Exercice 1

In [3]:
"""
Créer un tableau depuis la liste [1.6, 0.5, 7.4, 22.3] et stocker le dans la variable « vec ».
o Afficher le contenu de la variable « vec »
o Afficher le type de données du tableau « vec », sa forme, sa dimension et sa longueur.
o Afficher le troisième élément du tableau.
o Modifier la valeur « 0.5 » par « 3.8 ».
o Calculer la taille de la mémoire du tableau.
o Convertir le type du tableau vers « int »
o Calculer la taille de la mémoire du tableau après la conversion du type.
o Sauvegarder le tableau dans un fichier texte
"""
vec: np.ndarray = np.array([1.6, 0.5, 7.4, 22.3])
info(f"Vec: {vec}")
debug(f"Type: {vec.dtype}, Shape: {vec.shape}, Dimension: {vec.ndim}, Length: {len(vec)}")
info(f"3rd Element: {vec[2]}")
vec[1] = 3.8
info(f"Memory Size: {vec.nbytes}, calculated: {vec.size * vec.itemsize}")
vec = vec.astype(int)
info(f"Memory Size: {vec.nbytes}, calculated: {vec.size * vec.itemsize}")
np.savetxt("vec.txt", vec)

[INFO  14:16:43] Vec: [ 1.6  0.5  7.4 22.3]
[DEBUG 14:16:43] Type: float64, Shape: (4,), Dimension: 1, Length: 4
[INFO  14:16:43] 3rd Element: 7.4
[INFO  14:16:43] Memory Size: 32, calculated: 32
[INFO  14:16:43] Memory Size: 16, calculated: 16


In [4]:
"""
Créer une matrice « mat » depuis la liste [[0, 3, 6, 9], [5, 10, 15, 20], [30, 40, 50, 60]]
o Afficher le contenu de la variable « mat »
o Afficher le type de données de la matrice « mat », sa forme, sa dimension et sa longueur.
o Pouvez-vous obtenir la dimension et la longueur à partir de la forme ?
o Créer la matrice « mat_1 » extraite de « mat » telles que i >= 1, j <=2.
o Modifier la matrice « mat » afin que sa dernière ligne soit divisée par 10 et que sa première colonne soit multipliée par 2.
"""
mat: np.ndarray = np.array([
	[0, 3, 6, 9],
	[5, 10, 15, 20],
	[30, 40, 50, 60]
])
info(f"Mat:\n{mat}")
debug(f"Type: {mat.dtype}, Shape: {mat.shape}, Dimension: {mat.ndim}, Length: {len(mat)}")
info(f"Shape: {mat.shape}, Length: {mat.size} == {mat.shape[0] * mat.shape[1]}")
mat_1: np.ndarray = mat[1:, :3]
info(f"Mat_1:\n{mat_1}")

mat = mat.astype(float)	# Convert to float to avoid errors in division
mat[-1] /= 10
mat[:, 0] *= 2
info(f"Mat:\n{mat}")

[INFO  14:16:44] Mat:
[[ 0  3  6  9]
 [ 5 10 15 20]
 [30 40 50 60]]
[DEBUG 14:16:44] Type: int32, Shape: (3, 4), Dimension: 2, Length: 3
[INFO  14:16:44] Shape: (3, 4), Length: 12 == 12
[INFO  14:16:44] Mat_1:
[[ 5 10 15]
 [30 40 50]]
[INFO  14:16:44] Mat:
[[ 0.  3.  6.  9.]
 [10. 10. 15. 20.]
 [ 6.  4.  5.  6.]]


In [5]:
"""
Créer un tableau multidimensionnel « nd_vec » d’une dimension > 2
o Afficher le contenu de « nd_vec »
o Afficher le type de données du tableau « nd_vec », sa forme, sa dimension et sa longueur.
o Pouvez-vous obtenir la dimension et la longueur à partir de la forme ?
o Afficher un élément de ce tableau ainsi qu’un sous tableau
"""
nd_vec: np.ndarray = np.array([i+1 for i in range(12)])
nd_vec = nd_vec.reshape((2,2,3))
info(f"Nd_Vec:\n{nd_vec}")
debug(f"Type: {nd_vec.dtype}, Shape: {nd_vec.shape}, Dimension: {nd_vec.ndim}, Length: {len(nd_vec)}")
info(f"Shape: {nd_vec.shape}, Dimension: {nd_vec.ndim}, Length: {nd_vec.size} == {nd_vec.shape[0] * nd_vec.shape[1] * nd_vec.shape[2]}")
info(f"Element: {nd_vec[1, 1, 2]}")	# 3rd element of 2nd row of 2nd column
info(f"Sub-Array: {nd_vec[1, 1]}")	# 2nd row of 2nd column

[INFO  14:16:44] Nd_Vec:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[DEBUG 14:16:44] Type: int32, Shape: (2, 2, 3), Dimension: 3, Length: 2
[INFO  14:16:44] Shape: (2, 2, 3), Dimension: 3, Length: 12 == 12
[INFO  14:16:44] Element: 12
[INFO  14:16:44] Sub-Array: [10 11 12]


---
# Exercice 2

In [6]:
"""
• Créer un tableau 1D vide de taille 10 et de type « int » ; observer les valeurs du tableau.
• Créer un tableau 2D vide de dimension (3*3) et de type « float » ; observer les valeurs du tableau.
• Créer un tableau de 3 dimensions (3*3*3) initialisé avec des zéros « 0 ».
• Créer une matrice de taille (5*5) comportant des uns « 1 ».
• Créer un tableau de taille (10*10) initialisé avec la valeur « np.inf ».
• Créer une matrice d’identité de taille (4*4).
• Créer une matrice dont la diagonale est égale à [2, 3, 4, 5] et des 0 ailleurs.
"""
empty_1d: np.ndarray = np.empty(10, dtype=int)
info(f"Empty 1D: {list(empty_1d)}")	# list() for better formatting

empty_2d: np.ndarray = np.empty((3, 3), dtype=float)
debug(f"Empty 2D:\n{empty_2d}")

zero_3d: np.ndmatrix = np.zeros((3, 3, 3))
info(f"Zero 3D:\n{zero_3d}")

ones_2d: np.ndmatrix = np.ones((5, 5))
debug(f"Ones 2D:\n{ones_2d}")

inf_2d: np.ndmatrix = np.full((10, 10), np.inf)
info(f"Inf 2D:\n{inf_2d}")

eye_2d: np.ndarray = np.eye(4)
debug(f"Eye 2D:\n{eye_2d}")

diag_2d: np.ndarray = np.diag([2, 3, 4, 5])
info(f"Diag 2D:\n{diag_2d}")


[INFO  14:16:45] Empty 1D: [0, 0, 463621200, 578, 463619840, 578, 463619920, 578, 7274610, 7471207]
[DEBUG 14:16:45] Empty 2D:
[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [1.37962456e-306 1.16826648e-307 1.42413555e-306]
 [1.78019082e-306 4.79243676e-322 0.00000000e+000]]
[INFO  14:16:45] Zero 3D:
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
[DEBUG 14:16:45] Ones 2D:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[INFO  14:16:45] Inf 2D:
[[inf inf inf inf inf inf inf inf inf inf]
 [inf inf inf inf inf inf inf inf inf inf]
 [inf inf inf inf inf inf inf inf inf inf]
 [inf inf inf inf inf inf inf inf inf inf]
 [inf inf inf inf inf inf inf inf inf inf]
 [inf inf inf inf inf inf inf inf inf inf]
 [inf inf inf inf inf inf inf inf inf inf]
 [inf inf inf inf inf inf inf inf inf inf]
 [inf inf inf inf inf inf inf inf inf inf]
 [inf inf inf inf inf inf inf inf inf inf

---
# Exercice 3

In [7]:
"""
• Créer un tableau comportant la série d’entiers de 5 à 25 : [5, 6, 7, ... , 23,24,25]
• Créer un tableau contenant tous les entiers pairs entre 100 et 150 inclus.
• Créer un tableau qui comporte les dates du mois de Février 2019, ce tableau est de type « datetime64[D] »
• Créer un tableau de dix éléments équidistants entre 2 et 5 inclus.
"""
int_series: np.ndarray = np.arange(5, 26)
info(f"Int Series: {int_series}")
pair_series: np.ndarray = np.arange(100, 151, 2)
debug(f"Pair Series: {pair_series}")
date_array: np.ndarray = np.arange('2019-02', '2019-03', dtype='datetime64[D]')
info(f"Date Array: {date_array}")
equidist: np.ndarray = np.linspace(2, 5, 10)
debug(f"Equidist: {equidist}")

[INFO  14:16:45] Int Series: [ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]
[DEBUG 14:16:45] Pair Series: [100 102 104 106 108 110 112 114 116 118 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148 150]
[INFO  14:16:45] Date Array: ['2019-02-01' '2019-02-02' '2019-02-03' '2019-02-04' '2019-02-05'
 '2019-02-06' '2019-02-07' '2019-02-08' '2019-02-09' '2019-02-10'
 '2019-02-11' '2019-02-12' '2019-02-13' '2019-02-14' '2019-02-15'
 '2019-02-16' '2019-02-17' '2019-02-18' '2019-02-19' '2019-02-20'
 '2019-02-21' '2019-02-22' '2019-02-23' '2019-02-24' '2019-02-25'
 '2019-02-26' '2019-02-27' '2019-02-28']
[DEBUG 14:16:45] Equidist: [2.         2.33333333 2.66666667 3.         3.33333333 3.66666667
 4.         4.33333333 4.66666667 5.        ]


In [8]:
"""
• Soit la fonction y = f(x)= (ex – e-x)/(ex + e-x). Créer des tableaux x, y qui contiennent respectivement
 50 valeurs réparties uniformément sur [-5, 5] et l’évaluation de la fonction sur ces valeurs
"""
fx = lambda x: (np.exp(x) - np.exp(-x)) / (np.exp(x) + np.exp(-x))
x: np.ndarray = np.linspace(-5, 5, 50)
y: np.ndarray = fx(x)
info(f"\nX: {x}\nY: {y}")

[INFO  14:16:45] 
X: [-5.         -4.79591837 -4.59183673 -4.3877551  -4.18367347 -3.97959184
 -3.7755102  -3.57142857 -3.36734694 -3.16326531 -2.95918367 -2.75510204
 -2.55102041 -2.34693878 -2.14285714 -1.93877551 -1.73469388 -1.53061224
 -1.32653061 -1.12244898 -0.91836735 -0.71428571 -0.51020408 -0.30612245
 -0.10204082  0.10204082  0.30612245  0.51020408  0.71428571  0.91836735
  1.12244898  1.32653061  1.53061224  1.73469388  1.93877551  2.14285714
  2.34693878  2.55102041  2.75510204  2.95918367  3.16326531  3.36734694
  3.57142857  3.7755102   3.97959184  4.18367347  4.3877551   4.59183673
  4.79591837  5.        ]
Y: [-0.9999092  -0.99986344 -0.99979462 -0.99969111 -0.99953545 -0.99930137
 -0.99894941 -0.99842027 -0.99762495 -0.99642993 -0.99463525 -0.99194203
 -0.98790496 -0.9818637  -0.97284617 -0.9594368  -0.93960819 -0.91052931
 -0.86839883 -0.80841907 -0.72512414 -0.61335726 -0.47010419 -0.29690545
 -0.10168812  0.10168812  0.29690545  0.47010419  0.61335726  0.72512414
 

In [9]:
"""
• Écrire un programme NumPy qui permet de générer un nombre aléatoire entre 0 et 1.
• Créer un tableau de la dimension et de la taille de votre choix contenant des valeurs entre 34 et 76.
• Faites un tableau de forme (3, 5) avec des nombres aléatoires à partir d'une distribution normale standard
 (une distribution normale avec une moyenne 0 et une variance 1).
"""
np.random.seed(0)
rand_num: np.ndarray = np.random.rand()
debug(f"Random Number: {rand_num}")
rand_matrix: np.ndarray = np.random.randint(34, 76, size=(2, 2))
info(f"Random Array:\n{rand_matrix}")
rand_normal: np.ndarray = np.random.randn(3, 5)
debug(f"Random Normal Array:\n{rand_normal}")
info(f"Mean: {rand_normal.mean()}, Variance: {rand_normal.var()}")

[DEBUG 14:16:45] Random Number: 0.5488135039273248
[INFO  14:16:45] Random Array:
[[34 37]
 [37 73]]
[DEBUG 14:16:45] Random Normal Array:
[[ 1.86755799 -0.97727788  0.95008842 -0.15135721 -0.10321885]
 [ 0.4105985   0.14404357  1.45427351  0.76103773  0.12167502]
 [ 0.44386323  0.33367433  1.49407907 -0.20515826  0.3130677 ]]
[INFO  14:16:45] Mean: 0.4571297907048224, Variance: 0.5215681599180754


In [10]:
"""
• Créer une matrice (10x5) comportant des entiers aléatoires entre 0 et 100.
	o Standardiser cette matrice telle que chaque colonne aura une moyenne nulle et un écart type égal à 1.
"""
np.random.seed(0)
rand_matrix: np.ndarray = np.random.randint(0, 100, size=(10, 5))
info(f"Random Matrix:\n{rand_matrix}")
rand_matrix = (rand_matrix - rand_matrix.mean(axis=0)) / rand_matrix.std(axis=0)	# Axis=0 for column-wise operations
info(f"Standardized Matrix:\n{rand_matrix}")

# Verification
for i in range(rand_matrix.shape[1]):
	mean: float = rand_matrix[:, i].mean()
	std: float = rand_matrix[:, i].std()
	mean = round(mean, 5)	# Avoid floating point errors when comparing
	std = round(std, 5)		# Avoid floating point errors when comparing
	assert mean == 0, f"Mean of column {i} is not zero: {mean}"
	assert std == 1, f"Standard Deviation of column {i} is not 1: {std}"

[INFO  14:16:46] Random Matrix:
[[44 47 64 67 67]
 [ 9 83 21 36 87]
 [70 88 88 12 58]
 [65 39 87 46 88]
 [81 37 25 77 72]
 [ 9 20 80 69 79]
 [47 64 82 99 88]
 [49 29 19 19 14]
 [39 32 65  9 57]
 [32 31 74 23 35]]
[INFO  14:16:46] Standardized Matrix:
[[-0.02206157  0.          0.13173823  0.72539252  0.10755798]
 [-1.56637126  1.61579632 -1.48676006 -0.33034307  0.96802178]
 [ 1.12513992  1.84021247  1.03508612 -1.14768676 -0.27965074]
 [ 0.90452425 -0.35906585  0.99744662  0.0102168   1.01104497]
 [ 1.6104944  -0.44883231 -1.33620208  1.0659524   0.32267393]
 [-1.56637126 -1.21184724  0.73397016  0.7935045   0.62383626]
 [ 0.11030784  0.76301493  0.80924915  1.81518411  1.01104497]
 [ 0.1985541  -0.80789816 -1.56203905 -0.90929485 -2.17267111]
 [-0.24267724 -0.67324847  0.16937773 -1.24985473 -0.32267393]
 [-0.55153918 -0.7181317   0.50813319 -0.77307091 -1.26918412]]


---
# Exercice 4

In [11]:
"""
Créer une matrice aléatoire 10x10.
	o Sélectionner l'élément dans la première ligne et la première colonne.
	o Mettre l'élément de la dernière ligne et de la dernière colonne à -1.
	o Sélectionner les éléments de la deuxième ligne.
	o Sélectionner les éléments de la troisième colonne.
	o Remplacer tous les éléments de la deuxième ligne par 0.
"""
np.random.seed(0)
rand_matrix: np.ndarray = np.random.random(size=(10, 10))
info(f"Random Matrix:\n{rand_matrix}")
debug(f"Element [0, 0]: {rand_matrix[0, 0]}")
rand_matrix[-1, -1] = -1
debug(f"Element [-1, -1]: {rand_matrix[-1, -1]}")
info(f"2nd Row: {rand_matrix[1]}")
debug(f"3rd Column: {rand_matrix[:, 2]}")
rand_matrix[1] = 0
info(f"Modified 2nd Row:\n{rand_matrix}")

[INFO  14:16:46] Random Matrix:
[[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548  0.64589411
  0.43758721 0.891773   0.96366276 0.38344152]
 [0.79172504 0.52889492 0.56804456 0.92559664 0.07103606 0.0871293
  0.0202184  0.83261985 0.77815675 0.87001215]
 [0.97861834 0.79915856 0.46147936 0.78052918 0.11827443 0.63992102
  0.14335329 0.94466892 0.52184832 0.41466194]
 [0.26455561 0.77423369 0.45615033 0.56843395 0.0187898  0.6176355
  0.61209572 0.616934   0.94374808 0.6818203 ]
 [0.3595079  0.43703195 0.6976312  0.06022547 0.66676672 0.67063787
  0.21038256 0.1289263  0.31542835 0.36371077]
 [0.57019677 0.43860151 0.98837384 0.10204481 0.20887676 0.16130952
  0.65310833 0.2532916  0.46631077 0.24442559]
 [0.15896958 0.11037514 0.65632959 0.13818295 0.19658236 0.36872517
  0.82099323 0.09710128 0.83794491 0.09609841]
 [0.97645947 0.4686512  0.97676109 0.60484552 0.73926358 0.03918779
  0.28280696 0.12019656 0.2961402  0.11872772]
 [0.31798318 0.41426299 0.0641475  0.69247212 0.56

In [12]:
"""
• Écrire un programme NumPy pour inverser un tableau (le premier élément devient le dernier).
• Écrire un programme NumPy pour créer un tableau 2d avec 1 sur la bordure et 0 à l'intérieur.
• Écrire un programme NumPy pour créer une matrice 8x8 et remplissez-la avec un motif en damier.
"""
np.random.seed(0)
rand_matrix: np.ndarray = np.random.randint(0, 100, size=10)	# Easier to read than random.random()
info(f"Random Array:\n{rand_matrix}")
debug(f"Reversed Array:\n{rand_matrix[::-1]}")

rand_matrix: np.ndarray = np.ones((4, 4))
rand_matrix[1:-1, 1:-1] = 0		# 1:-1 to avoid the border
info(f"Border Matrix:\n{rand_matrix}")

checker_matrix: np.ndarray = np.zeros((8, 8))
checker_matrix[::2, 1::2] = 1	# Even rows, odd columns
checker_matrix[1::2, ::2] = 1	# Odd rows, even columns
debug(f"Checker Matrix:\n{checker_matrix}")

[INFO  14:16:46] Random Array:
[44 47 64 67 67  9 83 21 36 87]
[DEBUG 14:16:46] Reversed Array:
[87 36 21 83  9 67 67 64 47 44]
[INFO  14:16:46] Border Matrix:
[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]
[DEBUG 14:16:46] Checker Matrix:
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


---
# Exercice 5

In [13]:
"""
Écrire un programme NumPy dans lequel vous allez :
o Définir un tableau à une dimension de la taille de votre choix.
o Calculer l’écart type des valeurs présentes dans ce tableau.
o Chercher les valeurs et les indices des éléments qui sont supérieurs à « la moyenne des valeurs + 1.96 l’écart type ».
o Remplacer toutes ces valeurs par la valeur maximale du tableau.
o Chercher les valeurs et les indices des éléments qui sont inférieurs à « la moyenne des valeurs - 1.96 l’écart type ».
o Remplacer toutes ces valeurs par la valeur minimale du tableau
o Compter le nombre d’éléments égaux au maximum et le nombre d’éléments égaux au minimum.
o Compter le nombre d’éléments différents de min ou de max.
"""
rand_matrix: np.ndarray = np.array([0,1,1,1,1,1,1,16,81,256,625,1296,1300])
info(f"Random Array: {rand_matrix}")

std: float = rand_matrix.std()
debug(f"Standard Deviation: {std}")

mean: float = rand_matrix.mean()
info(f"Mean: {mean}")
compared_value: float = mean + 1.96 * std
info(f"Compared Value: {compared_value}")
indices: np.ndarray = np.where(rand_matrix > compared_value)
info(f"Indices: {indices}")
info(f"Values: {rand_matrix[indices]}")

rand_matrix[indices] = np.max(rand_matrix)
debug(f"Modified Array: {rand_matrix}")

compared_value = mean - 1.96 * std
info(f"Compared Value: {compared_value}")
indices = np.where(rand_matrix < compared_value)
info(f"Indices: {indices}")
info(f"Values: {rand_matrix[indices]}")

rand_matrix[indices] = np.min(rand_matrix)
debug(f"Modified Array: {rand_matrix}")

max_count: int = np.count_nonzero(rand_matrix == np.max(rand_matrix))
min_count: int = np.count_nonzero(rand_matrix == np.min(rand_matrix))
info(f"Max Count: {max_count}, Min Count: {min_count}")

others_count: int = np.count_nonzero((rand_matrix != np.min(rand_matrix)) & (rand_matrix != np.max(rand_matrix)))
alternative_count: int = len(rand_matrix) - max_count - min_count
debug(f"Others Count: {others_count}, Alternative Count: {alternative_count}")


[INFO  14:16:46] Random Array: [   0    1    1    1    1    1    1   16   81  256  625 1296 1300]
[DEBUG 14:16:46] Standard Deviation: 467.9515981646521
[INFO  14:16:46] Mean: 275.38461538461536
[INFO  14:16:46] Compared Value: 1192.5697477873337
[INFO  14:16:46] Indices: (array([11, 12], dtype=int64),)
[INFO  14:16:46] Values: [1296 1300]
[DEBUG 14:16:46] Modified Array: [   0    1    1    1    1    1    1   16   81  256  625 1300 1300]
[INFO  14:16:46] Compared Value: -641.8005170181028
[INFO  14:16:46] Indices: (array([], dtype=int64),)
[INFO  14:16:46] Values: []
[DEBUG 14:16:46] Modified Array: [   0    1    1    1    1    1    1   16   81  256  625 1300 1300]
[INFO  14:16:46] Max Count: 2, Min Count: 1
[DEBUG 14:16:46] Others Count: 10, Alternative Count: 10


---
# Exercice 6

In [14]:
"""
• Écrire un programme NumPy pour créer une matrice 3x3 avec des valeurs allant
de 2 à 10
• Créer la matricer suivante sans saisir explicitement ses valeurs :
[ [ 1, 6, 11],
[ 2, 7, 12],
[ 3, 8, 13],
[ 4, 9, 14],
[ 5, 10, 15] ]
"""
mat_1: np.ndarray = np.arange(2, 11).reshape(3, 3)		# Size argument is not available in arange
info(f"Mat_1:\n{mat_1}")

mat_2: np.ndarray = np.arange(1, 16).reshape(3, 5).T	# Transpose to get the desired shape
info(f"Mat_2:\n{mat_2}")

[INFO  14:16:47] Mat_1:
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
[INFO  14:16:47] Mat_2:
[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


In [19]:
"""
Diviser le tableau « s = np.arange(25).reshape(5,5)» afin de séparer chaque colonne à part.
Créer la matrice suivante en concaténant 3 tableaux unidimensionnel.
  Utiliser np.arange et np.ones pour la création des tableaux.
[ [ 7, 8, 9],
[ 1, 1, 1],
[ 12, 18, 2] ]
"""
s: np.ndarray = np.arange(25).reshape(5,5)
info(f"s:\n{s}")
s_split: np.ndarray = np.hsplit(s, s.shape[1])
info(f"s_split:\n{s_split}")

a: np.ndarray = np.arange(7, 10)
b: np.ndarray = np.ones(3)
c: np.ndarray = np.array([12, 18, 2])
mat_3: np.ndarray = np.vstack([a, b, c])
debug(f"Mat_3:\n{mat_3}")

[INFO  14:29:16] s:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[INFO  14:29:16] s_split:
[array([[ 0],
       [ 5],
       [10],
       [15],
       [20]]), array([[ 1],
       [ 6],
       [11],
       [16],
       [21]]), array([[ 2],
       [ 7],
       [12],
       [17],
       [22]]), array([[ 3],
       [ 8],
       [13],
       [18],
       [23]]), array([[ 4],
       [ 9],
       [14],
       [19],
       [24]])]
[DEBUG 14:29:16] Mat_3:
[[ 7.  8.  9.]
 [ 1.  1.  1.]
 [12. 18.  2.]]


---
# Exercice 7

In [30]:
"""
• Écrire un programme qui trouve les positions des éléments non nuls dans un tableau.
• Écrire un programme qui teste si aucun des éléments d'un tableau donné n'est nul.
• Utiliser la fonction numpy « np.pad » pour ajouter une bordure (remplie de 0) autour d'un tableau existant.
• Utiliser la fonction « np.asarray » pour créer un tableau à partir d’un tuple ou une liste.
• Tester la fonction « np.append » pour ajouter des éléments à la fin d’un tableau.
"""
np.random.seed(0)
rand_matrix: np.ndarray = np.random.randint(-1,1, size=(3,3))
info(f"Random Array:\n{rand_matrix}")
non_zero_indices: np.ndarray = np.nonzero(rand_matrix)
info(f"Non-Zero Indices:\n{non_zero_indices}")

is_non_zero: bool = np.all(rand_matrix != 0)
debug(f"Is Non-Zero:\n{is_non_zero}")

rand_matrix = np.pad(rand_matrix, 1)
info(f"Padded Array:\n{rand_matrix}")

as_array: np.ndarray = np.asarray([1, 2, 3, 4, 5])
debug(f"As Array:\n{as_array}")

rand_array: np.ndarray = np.append(rand_matrix, as_array)
info(f"Appended Array:\n{rand_array}")

[INFO  14:55:29] Random Array:
[[-1  0  0]
 [-1  0  0]
 [ 0  0  0]]
[INFO  14:55:29] Non-Zero Indices:
(array([0, 1], dtype=int64), array([0, 0], dtype=int64))
[DEBUG 14:55:29] Is Non-Zero:
False
[INFO  14:55:29] Padded Array:
[[ 0  0  0  0  0]
 [ 0 -1  0  0  0]
 [ 0 -1  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]]
[DEBUG 14:55:29] As Array:
[1 2 3 4 5]
[INFO  14:55:29] Appended Array:
[ 0  0  0  0  0  0 -1  0  0  0  0 -1  0  0  0  0  0  0  0  0  0  0  0  0
  0  1  2  3  4  5]


In [40]:
"""
• Utiliser la fonction «np.in1d » pour tester si chaque élément d'un tableau 1-D est également présent dans un second tableau.
• Utiliser la fonction « np.intersect1d» pour trouver des valeurs communes entre deux tableaux.
• Utiliser la fonction « np.tile » pour construire un tableau en répétant les éléments d’un autre tableau.
• Utiliser la fonction « bincount » pour compter le nombre d’occurrences de chaque valeur d’un tableau de valeurs positives
"""
series_1d: np.ndarray = np.arange(10)
reversed_1d: np.ndarray = np.arange(5, 15)
info(f"Series 1D:\n{series_1d}")
info(f"Reversed 1D:\n{reversed_1d}")
info(f"In 1D:\n{np.in1d(series_1d, reversed_1d)}")

common_values: np.ndarray = np.intersect1d(series_1d, reversed_1d)
debug(f"Common Values:\n{common_values}")

tiled_array: np.ndarray = np.tile(series_1d, 2)	# Repeat twice
info(f"Tiled Array:\n{tiled_array}")

occurences: np.ndarray = np.bincount(tiled_array)
debug(f"Occurences:\n{occurences}")

[INFO  15:19:21] Series 1D:
[0 1 2 3 4 5 6 7 8 9]
[INFO  15:19:21] Reversed 1D:
[ 5  6  7  8  9 10 11 12 13 14]
[INFO  15:19:21] In 1D:
[False False False False False  True  True  True  True  True]
[DEBUG 15:19:21] Common Values:
[5 6 7 8 9]
[INFO  15:19:21] Tiled Array:
[0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9]
[DEBUG 15:19:21] Occurences:
[2 2 2 2 2 2 2 2 2 2]


---
# Exercice 8

In [ ]:
"""
Utiliser la librairie numpy pour lire un fichier représentant une « dataset ».
Utiliser la fonction numpy.genfromtxt() pour lire le fichier « titanic.csv » dans un tableau qu’on nommera "donnees".
• Afficher le type de la variable donnees en utilisant la fonction type()
• Afficher sa dimension, sa forme, etc
• Apporter des modifications à votre base et sauvegarder la nouvelle base dans un fichier « titanic_mod.csv»
"""
donnees: np.ndarray = np.genfromtxt("titanic.csv", delimiter=",", skip_header=1)	# Skip header and read as csv
info(f"Type: {type(donnees)}")
debug(f"Shape: {donnees.shape}, Dimension: {donnees.ndim}, Length: {len(donnees)}")

# Modifications
donnees[:, 1] = donnees[:, 1] * 2	# Double the 2nd column
donnees[:, 2] = donnees[:, 2] / 2	# Half the 3rd column

# Save as csv
np.savetxt("titanic_mod.csv", donnees, delimiter=",")	# Save as csv